SDClowen/RSBot

Application/RSBot/Views/Controls/Entity.cs, Library/RSBot.Core/Client/ReferenceObjects/RefObjItem.cs, Library/RSBot.Core/Extensions/MonsterRarityExtensions.cs, Plugins/RSBot.Inventory/RSBot.Inventory.csproj, Plugins/RSBot.Inventory/Views/Main.Designer.cs, Plugins/RSBot.Inventory/Views/Main.cs, Plugins/RSBot.Inventory/Views/UseItemDialog.Designer.cs, Plugins/RSBot.Inventory/Views/UseItemDialog.cs, Plugins/RSBot.Inventory/Views/UseItemDialog.resx, Plugins/RSBot.Map/Views/Main.cs
Added feature to use items on ui.
Reload button removed
=> Updated inventory item plugin

Plugins/RSBot.Map/Views/Main.Designer.cs, Plugins/RSBot.Skills/Views/Main.Designer.cs, Plugins/RSBot.Skills/Views/Main.cs
Fixed duplicate problem due to id when action_overlap:0
=> Fixed skill adding(duplicate)

Plugins/RSBot.Shopping/Views/Main.cs
=> Fixed wrong pickup item setting in Main form

Plugins/RSBot.General/Components/AutoLogin.cs
=> Increase delay on autologin to fix maxiguard error

Library/RSBot.Core/Components/PickupManager.cs, Library/RSBot.Core/Objects/Player.cs, Library/RSBot.Core/Objects/Spawn/SpawnedBionic.cs, Library/RSBot.Core/Objects/Spawn/SpawnedItem.cs
=> Optimize pickuping

Library/RSBot.Core/Client/ReferenceObjects/RefObjCommon.cs, Library/RSBot.Core/GameClientType.cs, Library/RSBot.Core/Objects/InventoryItem.cs, Library/RSBot.Core/Objects/State.cs, Plugins/RSBot.General/Views/Main.cs
Added support for vietnam 193 client (vsro 193)
=> Add support for vietnam 193 (vsro 193)

Library/RSBot.Core/Objects/Spawn/SpawnedBionic.cs, Plugins/RSBot.Map/Views/Main.Designer.cs, Plugins/RSBot.Map/Views/Main.cs, Plugins/RSBot.Map/Views/Main.resx
=> Added feature auto select unique monsters #38

Application/RSBot/Views/Main.cs
=> Users can create their own color array in the custom color dialog

Library/RSBot.Core/RSBot.Core.csproj, Library/RSBot.Core/Temp.Theme/Controls/Separator.cs, Plugins/RSBot.Party/Bundle/AutoParty/AutoPartyBundle.cs, Plugins/RSBot.Party/Bundle/AutoParty/AutoPartyConfig.cs, Plugins/RSBot.Party/Views/Main.Designer.cs, Plugins/RSBot.Party/Views/Main.cs
=> Added new feature #131

Library/RSBot.Core/Components/SkillManager.cs, Library/RSBot.Core/Network/AwaitCallback.cs, Library/RSBot.Core/Network/PacketManager.cs, Library/RSBot.Core/Objects/Cos/AbilityPet.cs, Library/RSBot.Core/Objects/Cos/Vehicle.cs, Library/RSBot.Core/Objects/Inventory.cs, Library/RSBot.Core/Objects/InventoryItem.cs, Library/RSBot.Core/Objects/Player.cs, Library/RSBot.Core/Objects/Spawn/SpawnedBionic.cs, Library/RSBot.Core/Objects/Spawn/SpawnedItem.cs, Plugins/RSBot.Party/Bundle/PartyMatching/PartyMatchingBundle.cs
Made AwaitCallback Thread-Safe.
Changed member names of AwaitCallbackResult to more expressive.
Cleaned and commented.
=> FixAwaitCallback

Application/RSBot/Views/ScriptRecorder.cs, Library/RSBot.Core/Components/ScriptManager.cs, Plugins/RSBot.Shopping/Views/Main.cs
LoadShoppingList just clears the ShoppingList.
=> Fix No Shopping and Script Move

Application/RSBot/Views/Controls/Character.cs, Library/RSBot.Core/Network/Handler/Agent/Character/CharacterIncreaseIntResponse.cs, Library/RSBot.Core/Network/Handler/Agent/Character/CharacterIncreaseStrResponse.cs, Library/RSBot.Core/Network/Handler/Agent/Entity/EntityAnimationPromoteResponse.cs, Library/RSBot.Core/Network/Handler/Agent/Entity/EntityUpdateExperienceResponse.cs, Library/RSBot.Core/Objects/Player.cs, Plugins/RSBot.General/Components/AutoLogin.cs, Plugins/RSBot.General/PacketHandler/CharacterListing.cs, Plugins/RSBot.Protection/Bootstrap.cs, Plugins/RSBot.Protection/Components/Player/StatPointsHandler.cs, Plugins/RSBot.Protection/Components/Town/LevelUpHandler.cs, Plugins/RSBot.Protection/RSBot.Protection.csproj, Plugins/RSBot.Protection/Views/Main.Designer.cs, Plugins/RSBot.Protection/Views/Main.cs, Plugins/RSBot.Statistics/Views/Main.cs
[Feature]
* Add a feature that automatically distributes stat points to STR/INT depending on the user's configuration.
[Bugfix]
* Fix crash if auto login tries to login a deleted char
* Fix level and EXP display and event handling fixes #221
=> [Feature] Add auto increase int/str function

Plugins/RSBot.Skills/Components/LearnMasteryHandler.cs, Plugins/RSBot.Skills/RSBot.Skills.csproj, Plugins/RSBot.Skills/Views/Main.Designer.cs, Plugins/RSBot.Skills/Views/Main.cs
[Feature]
* Add new option to auto increase the mastery level
=> [Feature] Add auto learn mastery

Library/RSBot.Core/Client/ReferenceObjects/RefObjItem.cs, Library/RSBot.Core/Components/SkillManager.cs, Library/RSBot.Core/Network/Handler/Agent/Action/ActionSkillCastResponse.cs, Library/RSBot.Core/Objects/Inventory.cs, Library/RSBot.Core/Objects/InventoryItem.cs, Library/RSBot.Core/Objects/Player.cs
[Bugfix]
* Fix a bug that resulted in an endless loop if the bot tries to equip a better item but the player does not fit the requirements to equip it
* Fix some typos
=> [Bugfix] Fix bug if bot tries to equip an item that can not be equiped

Library/RSBot.Core/Objects/Skills.cs, Plugins/RSBot.Skills/RSBot.Skills.csproj, Plugins/RSBot.Skills/Views/Main.Designer.cs, Plugins/RSBot.Skills/Views/Main.cs, Plugins/RSBot.Skills/Views/SkillProperties.Designer.cs, Plugins/RSBot.Skills/Views/SkillProperties.cs, Plugins/RSBot.Skills/Views/SkillProperties.resx
[Bugfix] 
* Fixes #248 
[Feature]
* Add skill debug window if in developer mode. Can be opened by double clicking on a skill from the list
=> Fixes #248; Adds feature skill debug info if in dev mode

Application/RSBot/Views/About.Designer.cs, Application/RSBot/Views/ExitDialog.Designer.cs, Application/RSBot/Views/Main.Designer.cs, Application/RSBot/Views/ScriptRecorder.Designer.cs, Application/RSBot/Views/SplashScreen.Designer.cs, Plugins/RSBot.General/Views/Accounts.Designer.cs, Plugins/RSBot.General/Views/Accounts.cs, Plugins/RSBot.General/Views/PendingWindow.Designer.cs, Plugins/RSBot.General/Views/PendingWindow.cs, Plugins/RSBot.Inventory/Views/ItemProperties.Designer.cs, Plugins/RSBot.Inventory/Views/Main.cs, Plugins/RSBot.Inventory/Views/UseItemDialog.Designer.cs, Plugins/RSBot.Protection/Views/Main.Designer.cs, Plugins/RSBot.Protection/Views/Main.cs
=> Fixed glitches and irregularities on the UI.

Application/RSBot/Views/ExitDialog.Designer.cs, Application/RSBot/Views/Main.cs
=> Change logo and fix big window in exit dialog

Application/RSBot/Views/ScriptRecorder.cs, Library/RSBot.Core/Components/Scripting/Commands/MoveScriptCommand.cs, Library/RSBot.Core/Components/Scripting/Commands/SkillCastScriptCommand.cs, Library/RSBot.Core/Objects/Player.cs, Library/RSBot.Core/Objects/Skills.cs, Library/RSBot.Core/RSBot.Core.csproj
[Features]
* Adds a new script command "cast" that is able to cast buffs
=> [Feature] Add cast script command

Botbases/RSBot.Bot.Default/Bundle/Attack/AttackBundle.cs, Botbases/RSBot.Bot.Default/Views/Main.Designer.cs, Botbases/RSBot.Bot.Default/Views/Main.cs, Plugins/RSBot.General/Views/Main.Designer.cs, Plugins/RSBot.Map/Views/Main.Designer.cs, Plugins/RSBot.Map/Views/Main.cs
* Feature: Train area drawing in the map plugin
@SDClowen 
I also removed the completely not working and there for useless debug buttons from years ago
=> [Fix] Several map improvements; [Fix] UI issues

Plugins/RSBot.Statistics/RSBot.Statistics.csproj
Remove forgetten old theme library in statistics plugin
Updated submodule
=> Remove forgetten old theme library in statistics plugin

Botbases/RSBot.Default/Views/Main.cs, Plugins/RSBot.Skills/Views/Main.cs
=> [ISSUE-297] Fix imbue after skill level up

Application/RSBot/Views/ScriptRecorder.cs, Botbases/RSBot.Default/Bootstrap.cs, Botbases/RSBot.Default/Bundle/Attack/AttackBundle.cs, Botbases/RSBot.Default/Bundle/Avoidance/AvoidanceBundle.cs, Botbases/RSBot.Default/Bundle/Berzerk/BerzerkBundle.cs, Botbases/RSBot.Default/Bundle/Buff/BuffBundle.cs, Botbases/RSBot.Default/Bundle/Bundles.cs, Botbases/RSBot.Default/Bundle/IBundle.cs, Botbases/RSBot.Default/Bundle/Loop/LoopBundle.cs, Botbases/RSBot.Default/Bundle/Loot/Lootbundle.cs, Botbases/RSBot.Default/Bundle/Movement/MovementBundle.cs, Botbases/RSBot.Default/Bundle/PartyBuffing/PartyBuffingBundle.cs, Botbases/RSBot.Default/Bundle/Resurrect/ResurrectBundle.cs, Botbases/RSBot.Default/Bundle/Target/TargetBundle.cs, Library/RSBot.Core/Components/PickupManager.cs, Library/RSBot.Core/Components/ScriptManager.cs, Library/RSBot.Core/Components/SkillManager.cs, Library/RSBot.Core/Game.cs, Library/RSBot.Core/Network/AwaitCallback.cs, Library/RSBot.Core/Network/Handler/Agent/Action/ActionSkillCastResponse.cs, Library/RSBot.Core/Network/Handler/Agent/Entity/EntityUpdatePositionResponse.cs, Library/RSBot.Core/Network/Handler/Agent/Inventory/InventoryUpdateDurabilityResponse.cs, Library/RSBot.Core/Objects/CharacterInventory.cs, Library/RSBot.Core/Objects/Cos/Cos.cs, Library/RSBot.Core/Objects/Inventory/InventoryItem.cs, Library/RSBot.Core/Objects/Player.cs, Library/RSBot.Core/Objects/Spawn/SpawnedBionic.cs, Library/RSBot.Core/Objects/Spawn/SpawnedItem.cs, Plugins/RSBot.Party/Bundle/PartyMatching/PartyMatchingBundle.cs
* Fix spamming of HP/MP Potions
* Improve behavior if a mob is behind an obstacle
* Will try to select another mob now and if there is no other mob it will walk around
* It will retry to select the entity after 5 seconds
* Fix finding first entry point of a walk script
* Fix spamming of vehicle summon requests
=> [Fix] Improve bot loop

Library/RSBot.Core/Extensions/ListViewExtensions.cs, Library/RSBot.Core/Network/Handler/Agent/Action/ActionItemPerkAddResponse.cs, Library/RSBot.Core/Network/Handler/Agent/Action/ActionItemPerkRemoveResponse.cs, Library/RSBot.Core/Objects/ItemPerk.cs, Library/RSBot.Core/Objects/State.cs, Plugins/RSBot.Skills/Views/Main.cs
* Adds support for item perks such as EXP/SP Scrolls
=> [Feature] Add item perk information to active buffs

Botbases/RSBot.Default/Bundle/Loot/Lootbundle.cs, Library/RSBot.Core/Components/PickupManager.cs, Plugins/RSBot.Items/Views/Main.Designer.cs, Plugins/RSBot.Items/Views/Main.cs
=> Optimized Pickup & Add pick blue items option

Library/RSBot.Core/Objects/Skill/SkillInfo.cs
Chinese chars did not buff at all because the DoT and cooldown handling was invalid.
I tested this fix with CH and EU chars but I cannot promise that every edge case skill is handled properly.
=> [Fix] Auto buff for chinese chars

Library/RSBot.Core/Network/PacketManager.cs, Library/RSBot.Core/Network/Socket/Client.cs, Library/RSBot.Core/Network/Socket/Server.cs
Just adding some more events without breaking/fixing anything else.
=> [Feature] Add "OnPacketSent" Event

Library/RSBot.Core/Client/ReferenceManager.cs, Library/RSBot.Core/Client/ReferenceObjects/RefExtraAbilityByEquipItemOptLevel.cs, Library/RSBot.Core/Objects/Inventory/InventoryItem.cs, Library/RSBot.Core/Objects/Player.cs
Can usable above csro clients
12dg or above mirror reflect skills
=> Add feature, for use extra ability item skills

Library/RSBot.Core/Bot.cs, Library/RSBot.Core/Kernel.cs, Library/RSBot.Core/Network/Handler/Agent/Cos/FellowStatUpdateResponse.cs, Library/RSBot.Core/Network/Handler/Agent/Entity/EntityUpdateStatusFlag.cs, Library/RSBot.Core/Network/Handler/Agent/Entity/EntityUpdateStatusResponse.cs, Library/RSBot.Core/Objects/Cos/Fellow.cs
Fixed recovery handling
Fixed max-hp detecting
We are now knows the fellow stats and inventory, but need extra stuffs for show the inventory and stat data on ui
=> Fix and detailed fellow pets

Dependencies/Languages/RSBot.Default/العربية.rsl, Dependencies/Languages/RSBot.General/العربية.rsl
=> Arabic Update

Application/RSBot/Helper/ProfilePathHelper.cs, Application/RSBot/Views/Dialog/ProfileSelectionDialog.Designer.cs, Application/RSBot/Views/Dialog/ProfileSelectionDialog.cs, Application/RSBot/Views/Main.cs, Library/RSBot.Core/Config/GlobalConfig.cs, Plugins/RSBot.General/Components/Accounts.cs
Fixed issue #331 
Use Data\User path instead of \User
Show window at centered
Removed link label for remove profile, use red button for remove the selected profile
Removed new item in combobox for add new profile, use green button for add new one
=> Fixed issue #331

Plugins/RSBot.Skills/Views/Main.cs
=> Fixed issue #335

Application/RSBot/Helper/ProfilePathHelper.cs, Botbases/RSBot.Default/RSBot.Default.csproj, Library/RSBot.Core/Config/GlobalConfig.cs, Library/RSBot.Core/Config/PlayerConfig.cs, Plugins/RSBot.Chat/RSBot.Chat.csproj, Plugins/RSBot.General/Components/Accounts.cs, Plugins/RSBot.General/RSBot.General.csproj, Plugins/RSBot.Inventory/RSBot.Inventory.csproj, Plugins/RSBot.Items/RSBot.Items.csproj, Plugins/RSBot.Log/RSBot.Log.csproj, Plugins/RSBot.Map/RSBot.Map.csproj, Plugins/RSBot.Party/RSBot.Party.csproj, Plugins/RSBot.Protection/RSBot.Protection.csproj, Plugins/RSBot.Skills/RSBot.Skills.csproj, Plugins/RSBot.Statistics/RSBot.Statistics.csproj
=> Changed folder structures

Botbases/RSBot.Default/Bundle/Loot/Lootbundle.cs, Library/RSBot.Core/Components/PickupManager.cs, Library/RSBot.Core/Components/ShoppingManager.cs, Library/RSBot.Core/Objects/Spawn/SpawnedItem.cs
Still a known issue:
Sometimes the player does not pickup the item correctly but this PR helps alot to reduce the stucks of the pickup manager
=> Fix item picking

Plugins/RSBot.Statistics/Stats/Calculators/Live/ExperiencePerHour.cs, Plugins/RSBot.Statistics/Stats/Calculators/Live/GoldPerHour.cs, Plugins/RSBot.Statistics/Stats/Calculators/Live/KillsPerHour.cs, Plugins/RSBot.Statistics/Stats/Calculators/Live/LootPerHour.cs, Plugins/RSBot.Statistics/Stats/Calculators/Live/SkillPointsPerHour.cs, Plugins/RSBot.Statistics/Stats/Calculators/Static/BottingTime.cs, Plugins/RSBot.Statistics/Stats/Calculators/Static/Experience.cs, Plugins/RSBot.Statistics/Stats/Calculators/Static/Gold.cs, Plugins/RSBot.Statistics/Stats/Calculators/Static/Kills.cs, Plugins/RSBot.Statistics/Stats/Calculators/Static/LevelUps.cs, Plugins/RSBot.Statistics/Stats/Calculators/Static/Loot.cs, Plugins/RSBot.Statistics/Stats/Calculators/Static/SkillPoints.cs, Plugins/RSBot.Statistics/Stats/IStatisticCalculator.cs, Plugins/RSBot.Statistics/Stats/StatisticsGroup.cs, Plugins/RSBot.Statistics/Views/Main.Designer.cs, Plugins/RSBot.Statistics/Views/Main.cs
=> Add botting time to statistics plugin

Library/RSBot.Core/Client/ReferenceObjects/RefObjItem.cs, Library/RSBot.Core/Objects/Inventory/InventoryItemCollection.cs
=> Fixed rarity name show

Application/RSBot/RSBot.csproj, Application/RSBot/Views/About.Designer.cs, Application/RSBot/Views/About.cs, Plugins/RSBot.Skills/Views/Main.cs
=> Fix issues #367

Library/RSBot.Core/Network/AwaitCallback.cs, Plugins/RSBot.Protection/Components/Pet/CosHGPRecoveryHandler.cs, Plugins/RSBot.Protection/Components/Pet/CosHealthRecoveryHandler.cs, Plugins/RSBot.Protection/Components/Player/HealthManaRecoveryHandler.cs, Plugins/RSBot.Protection/Components/Player/SkillHealthHandler.cs, Plugins/RSBot.Protection/Components/Player/SkillManaHandler.cs, Plugins/RSBot.Protection/Components/Player/VigorRecoveryHandler.cs
Closes #373
Closes #372
Closes #368
=> Fix auto potion usings on protection plugin

Botbases/RSBot.Default/Bundle/Attack/AttackBundle.cs, Botbases/RSBot.Default/Bundle/Buff/BuffBundle.cs, Botbases/RSBot.Default/Bundle/Loop/LoopBundle.cs, Botbases/RSBot.Default/Bundle/Loot/Lootbundle.cs, Botbases/RSBot.Default/Bundle/Movement/MovementBundle.cs, Botbases/RSBot.Default/Bundle/PartyBuffing/PartyBuffingBundle.cs, Botbases/RSBot.Default/Bundle/Resurrect/ResurrectBundle.cs, Library/RSBot.Core/Components/PickupManager.cs, Library/RSBot.Core/Components/ScriptManager.cs, Library/RSBot.Core/Components/ShoppingManager.cs, Library/RSBot.Core/Components/SkillManager.cs
=> Add further status texts which indicate what the bot is actually doing

Library/RSBot.Core/Client/ReferenceObjects/RefObjItem.cs
Fix ref exception on newer clients
twsro, vsro 193, 274, TWSRo, csro, turkey, global, ksro
=> Fix null ref exception newer clients.

Botbases/RSBot.Default/Bundle/Attack/AttackBundle.cs, Botbases/RSBot.Default/Bundle/Buff/BuffBundle.cs, Library/RSBot.Core/ClientManager.cs, Library/RSBot.Core/Extensions/NativeExtensions.cs, Library/RSBot.Core/Network/Handler/Agent/Action/ActionBuffAddResponse.cs, Library/RSBot.Core/Network/Handler/Agent/Action/ActionBuffRemoveResponse.cs, Library/RSBot.Core/Objects/Skill/SkillInfo.cs
=> worked on #377

Plugins/RSBot.General/PacketHandler/GatewayPatchResponse.cs, Plugins/RSBot.General/PacketHandler/GatewayServerListRequestHook.cs
=> Fix issue #400

Botbases/RSBot.Default/Bundle/Attack/AttackBundle.cs, Botbases/RSBot.Default/Bundle/Buff/BuffBundle.cs, Botbases/RSBot.Default/Bundle/PartyBuffing/PartyBuffingBundle.cs, Botbases/RSBot.Default/Bundle/Resurrect/ResurrectBundle.cs, Library/RSBot.Core/Objects/Skill/SkillInfo.cs, Plugins/RSBot.Skills/Views/Main.Designer.cs, Plugins/RSBot.Skills/Views/Main.cs
Also its listening from script-recorder
=> Cast skill on ui, for your self or for party member

Application/RSBot/Views/Main.Designer.cs, Application/RSBot/Views/Main.cs, Botbases/RSBot.Default/Bootstrap.cs, Library/RSBot.Core/Plugins/BotbaseInfo.cs, Library/RSBot.Core/Plugins/BotbaseManager.cs
Change position and layout of the botbase selection to improve usability
Additional changes:
* Remove unused property "Image" from the botbases (can't be used anymore)
* Reformat and restructure the main window code to have a cleaner look
=> Update botbase selection element

Botbases/RSBot.Default/Bot/Objects/TrainingArea.cs, Botbases/RSBot.Default/Views/Dialogs/CreateTrainingAreaDialog.Designer.cs, Botbases/RSBot.Default/Views/Dialogs/CreateTrainingAreaDialog.cs, Botbases/RSBot.Default/Views/Dialogs/CreateTrainingAreaDialog.resx, Botbases/RSBot.Default/Views/Dialogs/TrainingAreasDialog.Designer.cs, Botbases/RSBot.Default/Views/Dialogs/TrainingAreasDialog.cs, Botbases/RSBot.Default/Views/Dialogs/TrainingAreasDialog.resx, Botbases/RSBot.Default/Views/Main.Designer.cs, Botbases/RSBot.Default/Views/Main.cs
=> Added new feature - Multitraining area

Plugins/RSBot.General/Components/Accounts.cs, Plugins/RSBot.General/PacketHandler/CharacterListing.cs, Plugins/RSBot.General/Views/Main.cs
Fix bugs related to the character selection before entering the game
=> Fix character listing bugs

Botbases/RSBot.Default/Bot/Botbase.cs, Botbases/RSBot.Default/Bot/Objects/TrainingArea.cs, Botbases/RSBot.Default/Bundle/Movement/MovementBundle.cs, Library/RSBot.Core/Client/ReferenceObjects/RefTeleport.cs, Library/RSBot.Core/Components/CollisionManager.cs, Library/RSBot.Core/Components/ScriptManager.cs, Library/RSBot.Core/Components/Scripting/Commands/MoveScriptCommand.cs, Library/RSBot.Core/Network/Handler/Agent/Entity/EntityUpdateMovementResponse.cs, Library/RSBot.Core/Network/Handler/Agent/Party/PartyUpdateResponse.cs, Library/RSBot.Core/Objects/Movement.cs, Library/RSBot.Core/Objects/Party/PartyMember.cs, Library/RSBot.Core/Objects/Position.cs, Library/RSBot.Core/Objects/Spawn/SpawnedEntity.cs, Plugins/RSBot.Map/Views/Main.cs, Plugins/RSBot.Party/Bundle/AutoParty/AutoPartyBundle.cs
The only doubt I had, it's about `Position` struct.
Why this is not a class with multiple constructors instead? Makes me feel weird having to use static methods to create instances.
Also, I removed the wrong parsing from movement packet.
I didn't get any useful values from that, not even on world map.
It was tested at vSRO 1.188 only, may need some review for another version tho.
Closes #3
=> Added dungeon layer maps #3

Application/RSBot/Views/Main.Designer.cs, Application/RSBot/Views/Main.cs, Application/RSBot/Views/Main.resx
=> Moved botbase list to top menu

Botbases/RSBot.Default/Bot/Botbase.cs, Botbases/RSBot.Default/Bundle/Target/TargetBundle.cs, Botbases/RSBot.Default/Views/Main.Designer.cs, Botbases/RSBot.Default/Views/Main.cs, Library/RSBot.Core/Client/ReferenceObjects/RefObjChar.cs
You can configure the ignore pillar at training tab.
=> Add standmode, ignore pillars and flowers

Plugins/RSBot.Statistics/Views/Main.Designer.cs, Plugins/RSBot.Statistics/Views/Main.cs, Plugins/RSBot.Statistics/Views/Main.resx
Just a quality of life feature. You can reset a single statistics entry with contextmenu
=> Added contextmenu to reset single statistic entry

Plugins/RSBot.Statistics/Stats/Calculators/Static/Experience.cs, Plugins/RSBot.Statistics/Stats/Calculators/Static/SkillPoints.cs
- fixed SP overflow when spending SP in mastery.
- fixed EXP calculation after lvl up.
=> Fixed static exp/sp statistics

Library/RSBot.Core/Network/Handler/Agent/Action/ActionBuffRemoveResponse.cs, Library/RSBot.Core/Network/Handler/Agent/Action/ActionSkillCastResponse.cs, Library/RSBot.Core/Objects/Spawn/SpawnedEntity.cs
The movement updater was stoping if the velocity was updated while the entity was walking. It's fixed now.
=> Fixed movement freezing while speed uptading.

Application/RSBot/Views/Main.Designer.cs, Application/RSBot/Views/Main.cs, Application/RSBot/Views/SplashScreen.cs
Supporting operating systems:
Windows 10 ver.1903 or above
Windows 11
https://user-images.githubusercontent.com/14323838/193384694-fe90c2e8-7d43-4cce-8a6c-4ac540d8d701.mp4
=> Auto theme, detect from system preference win10,11

Botbases/RSBot.Default/Bundle/Target/TargetBundle.cs
The orderby calls were - ironically - in the wrong order
=> Always prefer mobs that currently attack the player

Library/RSBot.Core/Kernel.cs, Library/RSBot.Core/Network/Handler/Agent/Cos/UpdateMountStateResponse.cs, Library/RSBot.Core/Network/Handler/Agent/Entity/EntityUpdateMovementResponse.cs, Library/RSBot.Core/Network/Handler/Agent/Entity/EntityUpdatePositionResponse.cs, Library/RSBot.Core/Objects/Cos/Cos.cs, Library/RSBot.Core/Objects/Movement.cs, Library/RSBot.Core/Objects/Player.cs
Fixed the bug of not making position updates in the pet's own class and some null errors.
=> Fixed the bug of not making position updates in the pet's

Library/RSBot.Core/Components/PickupManager.cs, Library/RSBot.Core/Network/Handler/Agent/Inventory/InventoryOperationResponse.cs, Library/RSBot.Core/Objects/ActionCommandType.cs, Library/RSBot.Core/Objects/ActionState.cs, Library/RSBot.Core/Objects/ActionType.cs, Library/RSBot.Core/Objects/Cos/Cos.cs, Library/RSBot.Core/Objects/Spawn/SpawnedItem.cs
* Fix bug where the ability pet won't pickup gold
* Fix bug if player is in action but tries to loot items
* Add enums for the action types
=> Fix several loot issues

Botbases/RSBot.Default/Bundle/Attack/AttackBundle.cs, Library/RSBot.Core/Components/PickupManager.cs, Library/RSBot.Core/Components/SkillManager.cs, Library/RSBot.Core/Network/Handler/Agent/Inventory/InventoryOperationResponse.cs, Library/RSBot.Core/Objects/ActionCommandType.cs, Library/RSBot.Core/Objects/ActionState.cs, Library/RSBot.Core/Objects/ActionType.cs, Library/RSBot.Core/Objects/Cos/Cos.cs, Library/RSBot.Core/Objects/Spawn/SpawnedItem.cs, Plugins/RSBot.Skills/Views/Main.Designer.cs, Plugins/RSBot.Skills/Views/Main.cs
* Adds a new option "use auto attack skill" to the skills plugin
⚠️ Merge after  #477
=> Add config for casting auto attack skill

Botbases/RSBot.Default/Bundle/Loop/LoopBundle.cs, Plugins/RSBot.Protection/Views/Main.Designer.cs
Added a config to auto-stop the bot after returning to town.
It's helpfull while the Sro-R medicine suppliers are not supported (I accidently ended up in a loop between training area and back to town because no potions in inventory. Bot used all my return scrolls for nothing xD)
=> Add config to stop bot after returned to town

Application/RSBot/Views/Dialog/ConfigDialog.Designer.cs, Application/RSBot/Views/Dialog/ConfigDialog.cs, Application/RSBot/Views/Dialog/ConfigDialog.resx, Application/RSBot/Views/Main.Designer.cs, Application/RSBot/Views/Main.cs, Library/RSBot.Core/Config/Config.cs, Library/RSBot.Core/Config/GlobalConfig.cs, Library/RSBot.Core/Extensions/SocketExtensions.cs, Library/RSBot.Core/Network/Packet.cs, Library/RSBot.Core/Network/Socket/Server.cs, Plugins/RSBot.General/Views/Main.cs
=> connect to target ip with socks4 proxy

Library/RSBot.Core/Objects/CharacterInventory.cs, Plugins/RSBot.Inventory/Bootstrap.cs, Plugins/RSBot.Inventory/Subscriber/InventoryUpdateSubscriber.cs, Plugins/RSBot.Inventory/Views/Main.Designer.cs, Plugins/RSBot.Inventory/Views/Main.cs
* Add auto sort function to player inventory
=> Add auto sort function to player inventory

Plugins/RSBot.Party/Bundle/AutoParty/AutoPartyBundle.cs, Plugins/RSBot.Party/Bundle/AutoParty/AutoPartyConfig.cs, Plugins/RSBot.Party/Bundle/PartyMatching/PartyMatchingBundle.cs, Plugins/RSBot.Party/Views/Main.Designer.cs, Plugins/RSBot.Party/Views/Main.cs
=> Added feature, join party matching by condition #501

Library/RSBot.Core/Objects/Player.cs
=> Fixed issue #505

Application/RSBot/Program.cs, Application/RSBot/Views/Dialog/ProfileSelectionDialog.cs, Library/RSBot.Core/Client/ReferenceManager.cs, Library/RSBot.Core/ClientManager.cs, Library/RSBot.Core/Components/ProfileManager.cs, Library/RSBot.Core/Kernel.cs, Library/RSBot.Core/LanguageManager.cs, Plugins/RSBot.Chat/Bootstrap.cs, Plugins/RSBot.General/Bootstrap.cs, Plugins/RSBot.General/Components/AutoLogin.cs, Plugins/RSBot.General/PacketHandler/AgentLoginResponse.cs, Plugins/RSBot.General/PacketHandler/CharacterListing.cs, Plugins/RSBot.Inventory/Bootstrap.cs, Plugins/RSBot.Items/Bootstrap.cs, Plugins/RSBot.Log/Bootstrap.cs, Plugins/RSBot.Map/Bootstrap.cs, Plugins/RSBot.Party/Bootstrap.cs, Plugins/RSBot.Skills/Bootstrap.cs, Plugins/RSBot.Skills/Components/LearnMasteryHandler.cs, Plugins/RSBot.Skills/Subscriber/LoadCharacterSubscriber.cs, Plugins/RSBot.Skills/Views/Dialog/SkillProperties.cs, Plugins/RSBot.Skills/Views/Main.cs, Plugins/RSBot.Skills/Views/View.cs, Plugins/RSBot.Statistics/Bootstrap.cs
(!) This PR adds the ability to boot the complete RSBot.Core from a terminal application
* Adds some additional debug logging
* Fix login account only loading  in UI mode
* Fix skills only in loading in UI mode
* If requested, I can include a CLI application to this PR but I see it as different repository, completely separated from this one
=> Improvement: Make RSBot core bootable in terminal mode

Plugins/RSBot.Inventory/Subscriber/InventoryUpdateSubscriber.cs, Plugins/RSBot.Inventory/Views/Main.cs
=> Fixed issue #513

Library/RSBot.Core/Client/ReferenceObjects/RefObjChar.cs, Library/RSBot.Core/Objects/NpcTalk.cs, Library/RSBot.Core/Objects/Skill/SkillInfo.cs
=> Fixed issue #514

Botbases/RSBot.Default/Views/Main.Designer.cs, Botbases/RSBot.Default/Views/Main.cs, Library/RSBot.Core/Extensions/MonsterRarityExtensions.cs, Library/RSBot.Core/Objects/MonsterRarity.cs, Library/RSBot.Core/Objects/Spawn/SpawnedMonster.cs, Plugins/RSBot.Skills/Views/Main.Designer.cs, Plugins/RSBot.Skills/Views/Main.cs
=> Added mob rarity for event mobs

Library/RSBot.Core/Components/CollisionManager.cs, Library/RSBot.Core/Game.cs, Plugins/RSBot.Map/Views/Main.cs
So its improving cpu using.
Closes #454
=> Disable drawing when map plugin is not visible

Botbases/RSBot.Default/Bundle/Target/TargetBundle.cs, Botbases/RSBot.Default/Views/Main.Designer.cs, Botbases/RSBot.Default/Views/Main.cs, Library/RSBot.Core/Objects/MonsterRarity.cs
* Adds a new option that will counter attack weaker mobs first in case of emergency.
* Closes https://github.com/SDClowen/RSBot/issues/495
=> Add option to auto select weaker mobs first in case of emergency

Library/RSBot.Core/Components/Collision/Calculated/CalculatedCollisionMesh.cs, Library/RSBot.Core/Components/Collision/RSCollisionLine.cs, Library/RSBot.Core/Components/Collision/RSCollisionMesh.cs, Library/RSBot.Core/Components/CollisionManager.cs, Library/RSBot.Core/Components/PickupManager.cs, Library/RSBot.Core/Game.cs, Library/RSBot.Core/Kernel.cs, Library/RSBot.Core/Objects/Spawn/SpawnedEntity.cs, Plugins/RSBot.Map/Views/Main.cs
* Reduces RAM usage and bot load time
* Fix bug where the collision detection was not working for spawned entities
=> Add lookup table for collisions

Botbases/RSBot.Default/Bundle/Movement/MovementBundle.cs, Plugins/RSBot.Party/Bundle/AutoParty/AutoPartyBundle.cs, Plugins/RSBot.Party/Bundle/AutoParty/AutoPartyConfig.cs, Plugins/RSBot.Party/Bundle/Commands/CommandsBundle.cs, Plugins/RSBot.Party/Views/Main.Designer.cs, Plugins/RSBot.Party/Views/Main.cs
=> Added feature, fallow party master issue #2

Botbases/RSBot.Default/Bundle/Attack/AttackBundle.cs, Library/RSBot.Core/Components/ClientManager.cs, Library/RSBot.Core/Components/SkillManager.cs, Library/RSBot.Core/Objects/Skill/SkillInfo.cs, Library/RSBot.Core/Objects/Spawn/SpawnedBionic.cs, Plugins/RSBot.Skills/Views/Main.Designer.cs, Plugins/RSBot.Skills/Views/Main.cs
* New feature: Use teleport skills
=> Add teleport skill feature

Library/RSBot.Core/Network/Handler/Agent/Entity/EntityUpdateStateResponse.cs, Library/RSBot.Core/Network/Handler/Agent/Entity/EntityUpdateStatusResponse.cs, Plugins/RSBot.Statistics/Stats/Calculators/Live/KillsPerHour.cs, Plugins/RSBot.Statistics/Stats/Calculators/Static/Kills.cs
* Fixes the kill counter in the statistics plugin
=> Fix statistics kill counter

Library/RSBot.Core/Components/SkillManager.cs
Fixes the position part of the packet
=> Fix teleportation position packet

Application/RSBot/Views/ScriptRecorder.cs, Botbases/RSBot.Default/Bootstrap.cs, Library/RSBot.Core/Bot.cs, Library/RSBot.Core/Network/Handler/Agent/Character/CharacterDataBeginResponse.cs, Library/RSBot.Core/Network/Handler/Agent/Character/CharacterDataEndResponse.cs, Library/RSBot.Core/Network/Handler/Agent/Cos/UpdateMountStateResponse.cs, Library/RSBot.Core/Network/Handler/Agent/Entity/EntityUpdateStateResponse.cs, Library/RSBot.Core/Network/Handler/Agent/Game/BuffTokenUpdateResponse.cs, Library/RSBot.Core/Network/Handler/Agent/Game/GameReadyRequest.cs, Library/RSBot.Core/Network/Handler/Agent/Game/GameResetCompleteResponse.cs, Library/RSBot.Core/Network/Handler/Agent/Party/PartyInviteResponse.cs, Library/RSBot.Core/Objects/Cos/JobTransport.cs, Library/RSBot.Core/Objects/Player.cs
* Fix bug where the player position was 0 after spawning a transport
* Fix bug where the client state was not detected correctly causing bots to continue eventhough the game is loading
=> Fix game ready state and transport position after spawn

Plugins/RSBot.Inventory/Views/Main.Designer.cs, Plugins/RSBot.Inventory/Views/Main.cs, Plugins/RSBot.Protection/Components/Town/DeadHandler.cs, Plugins/RSBot.Protection/Components/Town/DurabilityLowHandler.cs
It enables the automatic use of your items for the purpose.
Supported Items;
* Resurrection Scroll: When your character dies, it automatically respawns with this scroll.
* Repair Hammer: When the durability of your items decreases, it provides repair with an automatic repair hammer.
=> Inventory Plugin: Feature Auto Use Item According To Purpose

Library/RSBot.Core/Network/Handler/Agent/StorageBox/StorageBoxTakeItemResponse.cs
=> Fix detecting when got any item on item storage box window

Botbases/RSBot.Default/Bot/Botbase.cs, Botbases/RSBot.Default/Components/TrainingAreaScriptCommand.cs, Botbases/RSBot.Default/Views/Dialogs/TrainingAreasDialog.cs, Botbases/RSBot.Default/Views/Main.cs, Botbases/RSBot.Lure/Components/LureConfig.cs, Library/RSBot.Core/Client/ReferenceObjects/RefOptionalTeleport.cs, Library/RSBot.Core/Client/ReferenceObjects/RefTeleport.cs, Library/RSBot.Core/Client/ReferenceParser.cs, Library/RSBot.Core/Components/Collision/Calculated/CalculatedCollisionMesh.cs, Library/RSBot.Core/Components/ScriptManager.cs, Library/RSBot.Core/Components/Scripting/Commands/MoveScriptCommand.cs, Library/RSBot.Core/Objects/Area.cs, Library/RSBot.Core/Objects/Position.cs, Library/RSBot.Core/Objects/Region.cs, Plugins/RSBot.CommandCenter/Components/Command/AreaCommandExecutor.cs, Plugins/RSBot.Inventory/Views/Main.cs, Plugins/RSBot.Party/Bundle/AutoParty/AutoPartyBundle.cs
=> Fix cave issue #556

Library/RSBot.Core/Components/ClientManager.cs, Plugins/RSBot.General/Views/Main.cs
and fixed auto start client when dc
=> Sometimes, the client start button was disabling.

Botbases/RSBot.Default/Bundle/Attack/AttackBundle.cs, Botbases/RSBot.Default/Bundle/Movement/MovementBundle.cs, Botbases/RSBot.Default/Bundle/Target/TargetBundle.cs, Library/RSBot.Core/Client/ReferenceObjects/RefObjChar.cs, Library/RSBot.Core/Objects/Spawn/SpawnedItem.cs
**Optimized bot loop**
- Increased quality for target selecting (also its fixing trying to attack party member)
- Fix trying to attack spawned pandora-box
- Increased quality for skill using
closes #598 #597 #592
=> Optimized defaultbot loop

Library/RSBot.Core/Network/Handler/Agent/Alchemy/GenericAlchemyAckResponse.cs, Library/RSBot.Core/Network/Handler/Agent/Alchemy/GenericAlchemyRequestHandler.cs
=> Fix inventory updating after alchemy success

Botbases/RSBot.Default/Bot/Botbase.cs, Botbases/RSBot.Default/Bundle/PartyBuffing/PartyBuffingBundle.cs, Library/RSBot.Core/Objects/Spawn/SpawnedEntity.cs, Plugins/RSBot.Protection/Views/Main.cs
=> Fix skill buffs saving and using on protection plugin #525

Application/RSBot/Views/SplashScreen.Designer.cs, Botbases/RSBot.Default/Views/Dialogs/CreateTrainingAreaDialog.Designer.cs, Library/RSBot.Core/Components/ClientManager.cs, Library/RSBot.Core/Extensions/PacketExtensions.cs, Library/RSBot.Core/GameClientType.cs, Library/RSBot.Core/Network/Handler/Agent/Character/CharacterDataEndResponse.cs, Library/RSBot.Core/Network/Hooks/Agent/Inventory/BuyItemHook.cs, Library/RSBot.Core/Objects/Action.cs, Library/RSBot.Core/Objects/Inventory/InventoryItem.cs, Library/RSBot.Core/Objects/NpcTalk.cs, Plugins/RSBot.General/Components/AutoLogin.cs, Plugins/RSBot.General/PacketHandler/AgentLoginRequestHook.cs, Plugins/RSBot.General/PacketHandler/GatewayLoginRequest.cs, Plugins/RSBot.General/PacketHandler/GatewayServerListResponse.cs, Plugins/RSBot.General/PacketHandler/GlobalIdentificationRequest.cs
=> Added support for VTC-Game

Application/RSBot/Views/Main.cs
Improvement proposal for the user experience:
As a user, I expect the same behaviour when I click on the Close button than when I click on the menu: File -> Exit.
=> UX: Replicate the behaviour from the Close button to the menu: File -> Exit

Library/RSBot.Core/Components/ClientManager.cs
Closes #714
Closes #693 
Closes #691 
Closes #709
=> Fixed xincode on trsro

Botbases/RSBot.Default/Bot/Botbase.cs, Botbases/RSBot.Default/Bundle/Target/TargetBundle.cs, Library/RSBot.Core/Objects/State.cs
- Fixes a bug where the Botloop continues even if the bot is stopped (mutli threading issue)
- Fixes a bug where the TargetBundle would not return a new target
- Fixes a bug where the TargetBundle returned avoided targets
=> Fix target bundle not selecting any entity

Botbases/RSBot.Default/Bundle/PartyBuffing/PartyBuffingBundle.cs
refactored party buffing including the isBugged check for the active buff which was avoiding skill to be used on member
=> party buffing logic refactoring

Library/RSBot.Core/Network/Handler/Agent/Action/ActionBuffRemoveResponse.cs, Library/RSBot.Core/Objects/Skill/SkillInfo.cs
=> Fixed bard buffs expiration handling

Botbases/RSBot.Default/Bundle/PartyBuffing/PartyBuffingBundle.cs
- More accurate recognition of dead party members 
- Fixed rebuffing of inactive skills
=> Party buffing fixes

Library/RSBot.Core/Objects/Area.cs
=> Fix newPos equation as stated in issue (#825)

.github/nightly.yml
Runs monday of every week if there has been any commits and releases it as a pre-release.
Releases under:
- release name = RSBot.dd-mm-yyyy
- tag = dd-mm-yyyy
[example](https://github.com/Egezenn/RSBot/actions/runs/14772744847/job/41475504400)
=> Automated Nightly Releases

.github/workflows/nightly_build.yml, README.md
[Example](https://github.com/Egezenn/RSBot/releases/tag/2025-05-02)
=> Fix conditional release & readme update

Library/RSBot.Core/Components/Scripting/Commands/MoveScriptCommand.cs, Library/RSBot.Core/Network/Handler/Agent/Cos/AgentNotifyResponse.cs, Library/RSBot.Core/Objects/Cos/Cos.cs, Library/RSBot.Core/Objects/Cos/CosCommand.cs
=> Added support for riding on fellow pets and SP recall

Library/RSBot.Core/Network/Handler/Agent/Logout/LogoutSuccessResponse.cs, Plugins/RSBot.Party/Bundle/PartyMatching/Network/PartyMatchingDeleteResponse.cs, Plugins/RSBot.Party/Bundle/PartyMatching/Network/PartyMatchingFormResponse.cs, Plugins/RSBot.Party/Bundle/PartyMatching/Network/PartyMatchingInviteRequest.cs, Plugins/RSBot.Party/Bundle/PartyMatching/PartyMatchingBundle.cs, Plugins/RSBot.Party/Views/Main.cs
- Fixed a bug with the first char who joined through party matching being duplicated
- Added handling of changing party leader
- Added party matching re-creation when member left
- Added party matching re-creation every 20 minutes
- Added party matching re-creation on login
Closes #838, closes #869
=> Party matching improvements

Library/RSBot.Core/Extensions/PacketExtensions.cs, Library/RSBot.Core/Network/Handler/Agent/Character/CharacterDataEndResponse.cs, Library/RSBot.Core/Network/Packet.cs, Library/RSBot.Core/Objects/Action.cs, Library/RSBot.Core/Objects/CharacterInventory.cs, Library/RSBot.Core/Objects/Cos/Cos.cs, Library/RSBot.Core/Objects/NpcTalk.cs, Plugins/RSBot.General/Components/AutoLogin.cs, Plugins/RSBot.General/PacketHandler/AgentLoginRequestHook.cs, Plugins/RSBot.General/PacketHandler/GatewayServerListResponse.cs, Plugins/RSBot.General/PacketHandler/GlobalIdentificationRequest.cs, Plugins/RSBot.Inventory/Views/Main.cs
- Added support for relic items for KSRO and ISRO
- Fixed login on KSRO
- Fixed UTF-8 encoding on ISRO
- Fixed items counters in Inventory tab
=> Support of relic items
