Library/RSBot.Core/Components/CollisionManager.cs
If `offsetSource` and `offsetDestination` x-y value has 1920 same time, the `HasCollisionBetween` method always returning true.
=> temp fix for collision manager bug

Library/RSBot.Loader.Library/RSBot.Loader.Library.vcxproj
Fix 3 types Cpp Build Warnings
----------------------------
Microsoft.CppBuild.targets(500,5): warning MSB8004: Output Directory does not end with a trailing slash.  This build instance will add the slash as it is required to allow proper evaluation of the Output Directory.
-
1>Previous IPDB not found, fall back to full compilation.
1>All 547 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
-
1>detours.lib(detours.obj) : warning LNK4099: PDB 'detours.pdb' was not found with 'detours.lib(detours.obj)' or at 'SDClowen\RSBot\Build\detours.pdb'; linking object as if no debug info
1>detours.lib(modules.obj) : warning LNK4099: PDB 'detours.pdb' was not found with 'detours.lib(modules.obj)' or at 'SDClowen\RSBot\Build\detours.pdb'; linking object as if no …
=> FixCppBuildWarnings

Application/RSBot/Views/Main.Designer.cs, Application/RSBot/Views/Main.cs, Botbases/RSBot.Bot.Default/Bootstrap.cs, Botbases/RSBot.Bot.Default/Bundle/PartyBuffing/PartyBuffingBundle.cs, Dependencies/Languages/RSBot.Default/Deutsch.rsl, Dependencies/Languages/RSBot.Default/English.rsl, Dependencies/Languages/RSBot.Default/Español.rsl, Dependencies/Languages/RSBot.Default/Tiếng Việt.rsl, Dependencies/Languages/RSBot.Default/Türkçe.rsl, Library/RSBot.Core/Bot.cs, Library/RSBot.Core/LanguageManager.cs, Library/RSBot.Core/Objects/Spawn/SpawnedBionic.cs, Plugins/RSBot.Inventory/RSBot.Inventory.csproj, Plugins/RSBot.Inventory/Views/ItemProperties.Designer.cs, Plugins/RSBot.Inventory/Views/ItemProperties.cs, Plugins/RSBot.Inventory/Views/ItemProperties.resx, Plugins/RSBot.Inventory/Views/Main.Designer.cs, Plugins/RSBot.Inventory/Views/Main.cs
[Bugfix]
- Fix for the botbase tab translation
- Fix crash if a spawned bionic doesn't have a record
[Feature]
- Add new window "ItemProperties" to Inventory plugin
If the config `RSBot.DebugEnvironment` is set to `true`, the user is able to double click on an inventory item to see all internal properties. This makes implementing new ItemFilters alot easier and faster.
=> Fix translation and add item property window

Botbases/RSBot.Bot.Default/Bundle/Target/TargetBundle.cs, Library/RSBot.Core/Objects/Skill/SkillInfo.cs, Library/RSBot.Core/Objects/State.cs, Plugins/RSBot.Skills/Views/Main.Designer.cs, Plugins/RSBot.Skills/Views/Main.cs
- Added a new checkbox under advanced skill section:
- When warlock mode is active, bot will switch target when current target has at least 2 DoTs applied, and it will not select mobs that have at least 2 DoTs applied
- Warlock's DoT skills are now classified as attack skills and available in the skill selection list
=> [Feature] Warlock mode

Library/RSBot.Core/Objects/Player.cs, Plugins/RSBot.Protection/Components/Player/UniversalPillHandler.cs
- Universal and purification pills are now used based on bad effect detected on player character
- Bad status detection now runs on OnTick event, so pills can be used on cooldown while player has multiple bad statuses in effect 
- Slightly increased internal potion and pill cooldowns to prevent potions / pills being used before cooldown
=> Fixed issue #5

Library/RSBot.Core/Components/ShoppingManager.cs, Library/RSBot.Core/Network/Handler/Agent/Inventory/InventoryOperationResponse.cs, Library/RSBot.Core/Objects/Cos/AbilityPet.cs, Plugins/RSBot.Shopping/Views/Main.Designer.cs, Plugins/RSBot.Shopping/Views/Main.cs
- Added a new checkbox "Store items from pet" under Shopping tab's General Setup group:
- The checkbox modifies a new player config var "RSBot.Shopping.StorePetItems"
- When the config var is true and player has a grab pet summoned, items from pet's inventory that are set for storage will be stored
- Changed selling from pet logic: items will be moved to player and sold one by one to prevent a situation in which pet has more items than player's free inventory slots and not all items are sold
- Added item stack merging after buying
- Fixed invalid inventory update in following scenario:
Item x's max stack = 100
Item x in slot 1, amount 80
Item x in slot 2, amount 40
Move from slot 2 to slot 1, amount 20
Result before fix:
Item x in slot 1, amount 100
Item x in slot 2 removed
Result after …
=> [Feature] Store items from pet, shopping improvements

Application/RSBot/Views/Main.cs, Library/RSBot.Core/LanguageManager.cs, Plugins/RSBot.Shopping/Views/Main.cs
[Bugfix]
* Fix crash in RSBot.Shopping if the refItem could not be found
* Fix crash for plugins which are not being displayed as tab page (see image to get what I mean)
* Fix botbase and plugin name display if the translation was not found
=> [Bugfix] Fix crash in RSBot.Shopping if the refItem could not be found

Plugins/RSBot.Protection/Components/Town/AmmunitionHandler.cs, Plugins/RSBot.Protection/Components/Town/LevelUpHandler.cs, Plugins/RSBot.Protection/Components/Town/NoHealthPotionsHandler.cs, Plugins/RSBot.Protection/Components/Town/NoManaPotionsHandler.cs
[Feature/Bugfix]
* Add check for ammuntion and HP/MP potions when starting the bot, otherwise they will never be called if there were no items in the inventory in the first place
=> [Feature] Add check for ammunition and potions when the bot starts

Library/RSBot.Core/Components/Scripting/Commands/MoveScriptCommand.cs
Fixes a bug that stucks the bot if the player buffs during the walkscript. 
Cause:
The walkscript will continue eventhough the player is in action and there for loses the track of the current line resulting in "Distance too far" for the next steps
=> [Fix] script if player wants to move while buffing

.gitignore, Library/RSBot.Core/Client/ReferenceObjects/RefObjItem.cs
Costumes from group WK_COSTUME was being treated as job outfits, this caused spawn packet to be parsed incorrectly.
=> Fixed COSTUME_ETC being treated as job outfits

Botbases/RSBot.Default/Bot/Botbase.cs, Botbases/RSBot.Default/Bundle/Loot/Lootbundle.cs, Library/RSBot.Core/Bot.cs, Library/RSBot.Core/Components/PickupManager.cs
Seperated both logics into different methods due to misplaced pickup calls when item is marked as "Pickup by player only" while using an ability pet.
STR:
1. Setup an item to "Pickup by player only"
2. Configure bot to use ablilty-pet pickup
3. Spawn ability-pet
4. Go bezerk
5. Drop the item you marked as "pickup by player only"
6. Player will pick it up even when in bezerk due to missing conditions when using pet
And this is maybe the start to let the pickup pet run always even when the bot is stopped.
=> seperated pet pickup from player pickup

Botbases/RSBot.Default/Bundle/Loop/LoopBundle.cs, Library/RSBot.Core/Components/ScriptManager.cs, Library/RSBot.Core/Components/Scripting/Commands/MoveScriptCommand.cs
* If a move command failes (most likely due to server sync issues) it will be retried a maximum of 5 times.
* Walk scripts now always use the first script line if it was started right after a town script
=> Add retry logic for move commands

Botbases/RSBot.Default/Bundle/Attack/AttackBundle.cs, Library/RSBot.Core/Objects/Player.cs, Plugins/RSBot.Protection/Components/Pet/CosReviveHandler.cs
Fixed: The bot keeps spamming the spells eventhough it is technically unable to attack.
=> Add conditions for the player to be able to attack

Library/RSBot.Core/Extensions/PacketExtensions.cs
It wasn't read the party, chat etc etc strings because this client using unicode strings in packets
=> It wasn't read the party, chat etc etc strings because this client using unicode strings in packets

Library/RSBot.Core/Objects/CharacterInventory.cs
Fixes a bug where the bot tries to merge ammunition with freshly picked up ammunition resulting in buggy 5 seconds of switching slots around
=> Fix inventory sorting bug for the ammunition slot

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
This PR adds two GitHub issue templates for issue types that are used quite frequently in this repo.
Preview is [here](https://github.com/dvdblk/RSBot/issues/new/choose).
This also allows anyone to use the correct GitHub issue labels properly as they are added automatically with the template. By default, labels can [only be added by contributors](https://stackoverflow.com/a/13829505/4249857).
=> Add GitHub Issue templates

Library/RSBot.Core/Objects/CharacterInventory.cs, Library/RSBot.Core/Objects/Cos/Cos.cs, Library/RSBot.Core/Objects/Cos/CosCommand.cs, Library/RSBot.Core/Objects/Spawn/SpawnedEntity.cs
Fixed a bug where the pickup pet blocks the attack loop because the bot is waiting 5 seconds for the wrong server response.
=> Fix pet pickup packet awaiter blocking the attacking loop for 5 seconds

Application/RSBot.Replacer/Program.cs, Application/RSBot/Views/SplashScreen.cs, Application/RSBot/Views/Updater.cs, Library/RSBot.Core/Components/ClientManager.cs, Library/RSBot.Core/Components/CollisionManager.cs, Library/RSBot.Core/Components/LanguageManager.cs, Library/RSBot.Core/Components/ProfileManager.cs, Library/RSBot.Core/Components/ScriptManager.cs, Library/RSBot.Core/Config/GlobalConfig.cs, Library/RSBot.Core/Config/PlayerConfig.cs, Library/RSBot.Core/Extensions/NativeExtensions.cs, Library/RSBot.Core/Extensions/SocketExtensions.cs, Library/RSBot.Core/Kernel.cs, Library/RSBot.Core/Log.cs, Library/RSBot.Core/Plugins/BotbaseManager.cs, Library/RSBot.Core/Plugins/PluginManager.cs, Library/RSBot.Core/RSBot.Core.csproj, Plugins/RSBot.General/Components/Accounts.cs, Plugins/RSBot.Log/Views/Main.cs
This issue was having a problem with injecting the client and triggering the client library function.
Since v2.6 users have been solving this issue by moving the bot to another disk. It will probably be fixed with this pr.
=> Fix critical path-bug

Botbases/RSBot.Default/Bundle/Avoidance/AvoidanceBundle.cs, Botbases/RSBot.Default/Bundle/Berzerk/BerzerkBundle.cs, Botbases/RSBot.Default/Bundle/Buff/BuffBundle.cs, Library/RSBot.Core/Client/ReferenceObjects/RefSkill.cs, Library/RSBot.Core/Client/ReferenceObjects/SkillParams.cs, Library/RSBot.Core/Network/Handler/Agent/Entity/EntityUpdateStateResponse.cs, Library/RSBot.Core/Network/Handler/Agent/Game/BuffTokenUpdateResponse.cs, Library/RSBot.Core/Objects/Player.cs, Plugins/RSBot.CommandCenter/Components/Emoticons.cs, Plugins/RSBot.Inventory/Views/Main.cs, Plugins/RSBot.Items/Views/Main.Designer.cs, Plugins/RSBot.Items/Views/Main.cs, Plugins/RSBot.Skills/Views/Main.cs, RSBot.sln
- Fixes https://github.com/SDClowen/RSBot/issues/737
- Fixes avoid/prefer monster checks
- Fixes a bug where the pickup item filter wasn't loaded until a setting has changed
- Fixes a bug where pickup settings were not loaded after entering the game
- Fixes a bug where the teleportation/resurrection skills would not update in the UI
- Fixes a bug where the bot would buff eventhough the player is untouchable
=> Fix avoidance and preferance checks

Plugins/RSBot.Party/Views/Main.Designer.cs, Plugins/RSBot.Party/Views/Main.cs, Plugins/RSBot.Party/Views/Main.resx
new context menu added to party buff skills list to trigger refreshing party buff skills (in case of any uploading skill, list must be refreshed otherwise buff skill can not be found)
=> "Refresh Buffs" context menu added to Party Buff Skills list view

Library/RSBot.NavMeshApi/Dungeon/DungeonInfo.cs
When using BlackRogue Cap 100 client the dungeoninfo only has id and dungeonpath, no service.
This causes an exception on loading, and the Player object will be null, and it will cause infinite null reference exceptions
=> blackrogue dungeoninfo fix

Library/RSBot.Core/Network/Handler/Agent/Party/PartyUpdateResponse.cs, Library/RSBot.Core/Objects/Party/PartyUpdateType.cs
This pull request includes updates to the party system in the `RSBot.Core` library. The changes introduce a new `LeaderChange` type and handle this new type in the party update response method.
* [`Library/RSBot.Core/Objects/Party/PartyUpdateType.cs`](diffhunk://#diff-f56c051207cc954777f1aab1f5b2292ad5ee04c5f2ee0bf2292fc2742be5ace4L9-R10): Added a new `LeaderChange` type to the `PartyUpdateType` enum.
* [`Library/RSBot.Core/Network/Handler/Agent/Party/PartyUpdateResponse.cs`](diffhunk://#diff-676424346078898190da354e9469cbad8a4021343b9537d34dfb16e4ebb84475R117-R121): Added a case to handle the new `LeaderChange` type in the `PartyUpdateResponseCommon` method, updating the party leader and firing an event.
=> Enhance Party System: Add LeaderChange Type and Handle in Party Updates

Library/RSBot.Core/Network/Handler/Agent/Alchemy/GenericAlchemyAckResponse.cs, Library/RSBot.Core/Network/Handler/Agent/Game/GameResetCompleteResponse.cs
- Fixed an issue with teleportation in clientless when the bot would get stuck forever waiting for teleportation
- Fixed alchemy result packet structure, as a result alchemy works correctly with +2 and higher enhancing
=> Fixed teleporting in clientless and bug with alchemy

Library/RSBot.Core/Network/Handler/Agent/Game/GameResetCompleteResponse.cs
The intention to send this packet in clientless mode is clearly visible in the code (extra tabs). But the missing brackets causing the bot to send the packet in client mode, causing a null reference error after every teleportation.
=> Send Gamereset packet in clientless mode only

Library/RSBot.Core/Components/Scripting/Commands/TeleportScriptCommand.cs
Changed the opcode to wait for after executing teleportation while running a script. Previously, the bot got stuck waiting the 30 seconds timeout before moving on.
Took the other opcode from BuffTokenUpdateResponse packet
=> Change opcode to wait for after executing teleport

Application/RSBot/Views/Main.cs
DisplayAsTab should be false and View should be null. The plugin will still be displayed under the menuStrip gear, but nothing will happen when you click on it
=> Support for plugins without GUI

Botbases/RSBot.Lure/Bundle/MovementBundle.cs, Botbases/RSBot.Lure/Components/LureConfig.cs, Library/RSBot.Core/Components/Scripting/Commands/MoveScriptCommand.cs
Lure bot is using "Use mount if available" and "Use speed drug" checkboxes from Training botbase.
Now mount is not using during lure script.
=> Fixed riding on pet and using speed scrolls while luring

Plugins/RSBot.Party/Views/Main.cs
Now you can add Physical Screen and Morale Screen simultaneously, but the ability to add conflicting buffs (such as Body Deity and Angel's Body) has also been unlocked. You need to be more careful when configuring settings.
=> Fixed blocking the addition of party buffs
